# fly.toml app configuration file for argentum-bot
app = 'argentum-bot'
primary_region = 'gig'

[build]
  dockerfile = "Dockerfile"

[env]
  RUST_LOG = "info"

# Run as a single process
[processes]
  app = "./target/release/argentum-bot"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

# Keep the bot running continuously
[deploy]
  strategy = 'immediate'
  min_machines_running = 1
